# Generated by Django 3.1.7 on 2021-05-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_auto_20210504_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3d505a70-98c5-44ca-a2d6-11810c6b882e'), primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=1024)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_name', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
            ],
        ),
    ]
