# Generated by Django 3.1.7 on 2021-05-04 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20210504_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='id',
            field=models.UUIDField(default=uuid.UUID('607443c1-9fe6-4e56-b8c9-3c247f376854'), primary_key=True, serialize=False, unique=True),
        ),
    ]
