# Generated by Django 3.1.7 on 2021-05-04 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20210504_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
