# Generated by Django 3.1.7 on 2021-05-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210504_1515'),
        ('chats', '0004_auto_20210504_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
