# Generated by Django 3.1.7 on 2021-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20210510_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentMessage',
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
