# Generated by Django 3.1.7 on 2021-05-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210511_0619'),
        ('chats', '0007_auto_20210510_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user'),
        ),
    ]
