# Generated by Django 3.1.7 on 2021-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210504_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
