# Generated by Django 3.1.7 on 2021-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210504_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
