# Generated by Django 3.1.7 on 2021-05-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210504_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='socket_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
    ]
