# Generated by Django 3.1.7 on 2021-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210511_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='socket_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
